/*
 * Autogenerated container descriptions
 * defined for the current build.
 *
 * Copyright (C) 2009 Bahadir Balban
 */
#include <l4/generic/container.h>
#include <l4/generic/resource.h>
#include <l4/generic/capability.h>
#include <l4/generic/cap-types.h>
#include INC_PLAT(platform.h)
#include INC_PLAT(irq.h)


#define CONT0_PAGER_SIZE     0x5100

#if defined(CONFIG_CONT0_TYPE_LINUX)
    #define CONT0_PAGER_MAPSIZE \
                (CONT0_PAGER_SIZE + CONFIG_CONT0_LINUX_ZRELADDR - \
                 CONFIG_CONT0_LINUX_PHYS_OFFSET)
#else
    #define CONT0_PAGER_MAPSIZE (CONT0_PAGER_SIZE)
#endif



__initdata struct container_info cinfo[] = {

	[0] = {
	.name = "hello_world0",
	.npagers = 1,
	.ncaps = 2,
	.caps = {
			[0] = {
				.target = 0,
				.type = CAP_TYPE_IPC | CAP_RTYPE_CONTAINER,
				.access = CAP_IPC_SEND | CAP_IPC_RECV
				          | CAP_IPC_FULL | CAP_IPC_SHORT
				          | CAP_IPC_EXTENDED | CAP_CHANGEABLE
				          | CAP_REPLICABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0, .size = 0,
			},

			[1] = {
				.target = 0,
				.type = CAP_TYPE_QUANTITY | CAP_RTYPE_MUTEXPOOL,
				.access = CAP_CHANGEABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0,
				.size = 100,
			},

	},

	.pager = {
		[0] = {
			.start_address = (CONFIG_CONT0_START_PC_ADDR),
			.pager_lma = __pfn(CONFIG_CONT0_PAGER_LOAD_ADDR),
			.pager_vma = __pfn(CONFIG_CONT0_PAGER_VIRT_ADDR),
			.pager_size = __pfn(page_align_up(CONT0_PAGER_MAPSIZE)),
			.rw_pheader_start = 0xa0004000L,
			.rw_pheader_end = 0xa0005100L,
			.rx_pheader_start = 0xa0000000L,
			.rx_pheader_end = 0xa000359cL,
			.ncaps = 10,
			.caps = {

			[0] = {
				.target = 0,
				.type = CAP_TYPE_MAP_VIRTMEM | CAP_RTYPE_CONTAINER,
				.access = CAP_MAP_READ | CAP_MAP_WRITE | CAP_MAP_EXEC
					| CAP_MAP_CACHED | CAP_MAP_UNCACHED | CAP_MAP_UNMAP | CAP_MAP_UTCB |
					CAP_CACHE_INVALIDATE | CAP_CACHE_CLEAN,
				.start = __pfn(CONFIG_CONT0_PAGER_VIRT0_START),
				.end = __pfn(CONFIG_CONT0_PAGER_VIRT0_END),
				.size = __pfn(CONFIG_CONT0_PAGER_VIRT0_END - CONFIG_CONT0_PAGER_VIRT0_START),
			},

			[1] = {
				.target = 0,
				.type = CAP_TYPE_MAP_PHYSMEM | CAP_RTYPE_CONTAINER,
				.access = CAP_MAP_READ | CAP_MAP_WRITE | CAP_MAP_EXEC |
					CAP_MAP_CACHED | CAP_MAP_UNCACHED | CAP_MAP_UNMAP | CAP_MAP_UTCB,
				.start = __pfn(CONFIG_CONT0_PAGER_PHYS0_START),
				.end = __pfn(CONFIG_CONT0_PAGER_PHYS0_END),
				.size = __pfn(CONFIG_CONT0_PAGER_PHYS0_END - CONFIG_CONT0_PAGER_PHYS0_START),
			},

			[2] = {
				.target = 0,
				.type = CAP_TYPE_EXREGS | CAP_RTYPE_CONTAINER,
				.access = CAP_EXREGS_RW_PAGER
				          | CAP_EXREGS_RW_UTCB | CAP_EXREGS_RW_SP
				          | CAP_EXREGS_RW_PC | CAP_EXREGS_RW_REGS
				          | CAP_CHANGEABLE | CAP_REPLICABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0, .size = 0,
			},

			[3] = {
				.target = 0,
				.type = CAP_TYPE_IPC | CAP_RTYPE_CONTAINER,
				.access = CAP_IPC_SEND | CAP_IPC_RECV
				          | CAP_IPC_FULL | CAP_IPC_SHORT
				          | CAP_IPC_EXTENDED | CAP_CHANGEABLE
				          | CAP_REPLICABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0, .size = 0,
			},

			[4] = {
				.target = 0,
				.type = CAP_TYPE_TCTRL | CAP_RTYPE_CONTAINER,
				.access = CAP_TCTRL_CREATE | CAP_TCTRL_DESTROY
				          | CAP_TCTRL_SUSPEND | CAP_TCTRL_RUN
				          | CAP_TCTRL_RECYCLE | CAP_TCTRL_WAIT
				          | CAP_CHANGEABLE | CAP_REPLICABLE
				          | CAP_TRANSFERABLE,
				.start = 0, .end = 0, .size = 0,
			},

			[5] = {
				.target = 0,
				.type = CAP_TYPE_QUANTITY
					  | CAP_RTYPE_THREADPOOL,
				.access = CAP_CHANGEABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0,
				.size = 64,
			},

			[6] = {
				.target = 0,
				.type = CAP_TYPE_QUANTITY | CAP_RTYPE_MUTEXPOOL,
				.access = CAP_CHANGEABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0,
				.size = 100,
			},

			[7] = {
				/* For pmd accounting */
				.target = 0,
				.type = CAP_TYPE_QUANTITY | CAP_RTYPE_MAPPOOL,
				.access = CAP_CHANGEABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0,
				/* Function of mem regions, nthreads etc. */
				.size = 800,
			},

			[8] = {
				.target = 0,
				.type = CAP_TYPE_IRQCTRL | CAP_RTYPE_CONTAINER,
				.access = CAP_IRQCTRL_REGISTER | CAP_IRQCTRL_WAIT
				          | CAP_CHANGEABLE | CAP_REPLICABLE
				          | CAP_TRANSFERABLE,
				.start = IRQ_RANGE_START, .end = IRQ_RANGE_END, .size = 0,
			},

			[9] = {
				.target = 0,
				.type = CAP_TYPE_QUANTITY | CAP_RTYPE_SPACEPOOL,
				.access = CAP_CHANGEABLE | CAP_TRANSFERABLE,
				.start = 0, .end = 0,
				.size = 64,
			},

			},
		},

		},
	},

};
