import sys

Import('env')

# Get global paths
PROJRELROOT = '../../../'
sys.path.append(PROJRELROOT)

from scripts.config.configuration import *
config = configuration_retrieve()
platform = config.platform

#Platforms using 8250
plat_list = 'am1808'

# The set of source files associated with this SConscript file.
src_local = []

if plat_list == platform:
    src_local += Glob('*.c')

obj = env.StaticObject(src_local)
Return('obj')
