
Import('env')

from scripts.config.projpaths import *
from scripts.config.config_invoke import *

config = configuration_retrieve()
platform = config.platform

# The set of source files associated with this SConscript file.
src_local = []

# Platforms using pl190
plat_list = ['am1808', 'pb926']

if platform in plat_list:
    src_local += ['pl190_vic.c']

obj = env.Object(src_local)
Return('obj')
